name: .NET

on:
  push:
    branches: [ gRPC.Chat ]
  pull_request:
    branches: [ gRPC.Chat ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./gRPC.Chat.sln
    - name: Build
      run: dotnet build ./gRPC.Chat.sln --no-restore
    - name: Test
      run: dotnet test ./gRPC.Chat.sln --no-build --verbosity normal
